# Generated by Django 4.0 on 2022-01-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docs', '0002_doc_doctopic_folder_topic_delete_snippet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={},
        ),
        migrations.AlterField(
            model_name='doc',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='docs.folder'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='docs', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='folders', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='docs.folder'),
        ),
    ]
