# Generated by Django 4.0 on 2022-01-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docs', '0005_alter_folder_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctopic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.AlterField(
            model_name='doc',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='docs', to='docs.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='folders', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='folders', to='docs.folder'),
        ),
    ]
