# Generated by Django 4.0 on 2022-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_remove_doctopic_owner_remove_topic_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctopic',
            unique_together={('doc_id', 'topic_id')},
        ),
    ]
