# Generated by Django 4.0 on 2022-01-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_doctopic_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctopic',
            options={'ordering': ['doc_id']},
        ),
    ]
