# Generated by Django 4.0 on 2022-01-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docs', '0012_topic_docs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc',
            new_name='Document',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
